# Generated by Django 3.2.9 on 2021-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
